// src/pages/login/index.jsx
import { api, constant, isEmpty, md5 } from '@/common/utils';
import { LockTwoTone, UserOutlined } from '@ant-design/icons';
import { Alert, Button, Checkbox, Form, Input, Typography, message } from 'antd';
import { parse } from 'querystring';
import { useState } from 'react';
import { history, useIntl } from 'umi';
import styles from './index.less';
const { Title } = Typography;
const getPageQuery = () => parse(window.location.href.split('?')[1]);

const LoginMessage = ({ content }) => (
  <Alert
    style={{
      marginBottom: 24,
    }}
    message={content}
    type="error"
    showIcon
  />
);
export default (props) => {
  const { formatMessage } = useIntl(); //国际化
  const [loading, setLoading] = useState(false);
  //读取cookies
  const getCookie = (name) => {
    var arr,
      reg = new RegExp('(^| )' + name + '=([^;]*)(;|$)');
    if ((arr = document.cookie.match(reg))) return unescape(arr[2]);
    else return null;
  };

  // Form 数据
  const [form] = Form.useForm();
  const [checked, setChecked] = useState(getCookie(constant.SYSTEM_AVATAR_NAME + 'userPasswd') ? true : false);
  const [userName, setUserName] = useState(getCookie(constant.SYSTEM_AVATAR_NAME + 'userName'));
  const [userPasswd, setUserPasswd] = useState(getCookie(constant.SYSTEM_AVATAR_NAME + 'userPasswd'));
  const [errorMessage, setErrorMessage] = useState('');
  const [beError, setBeError] = useState(false);



  const handleToken = (token) => {
    let itoken;
    if (!isEmpty(token)) {
      itoken = `Bearer ${token}`;
      sessionStorage.setItem(constant.KEY_USER_TOKEN, itoken);
    }
  };

  const handleRemeberMe = (values) => {
    const { userName, originPassword, autoLogin } = values;
    var exp = new Date();
    exp.setTime(exp.getTime() + 7 * 24 * 60 * 60 * 1000);

    if (autoLogin) {
      document.cookie = constant.SYSTEM_AVATAR_NAME + 'userName' + "=" + escape(userName) + ';expires=' + exp.toGMTString();
      document.cookie = constant.SYSTEM_AVATAR_NAME + 'userPasswd' + "=" + escape(originPassword) + ";expires=" + exp.toGMTString();
      document.cookie = constant.SYSTEM_AVATAR_NAME + 'autoLogin' + "=" + escape(autoLogin) + ";expires=" + exp.toGMTString();
    } else {
      exp.setTime(exp.getTime() - 1);
      document.cookie = constant.SYSTEM_AVATAR_NAME + 'userName' + "=" + escape('') + ';expires=' + exp.toGMTString();
      document.cookie = constant.SYSTEM_AVATAR_NAME + 'userPasswd' + "=" + escape('') + ";expires=" + exp.toGMTString();
      document.cookie = constant.SYSTEM_AVATAR_NAME + 'autoLogin' + "=" + escape('') + ";expires=" + exp.toGMTString();
    }
    // const { userName, userPasswd, autoLogin, groupId } = values;
    // var exp = new Date();
    // exp.setTime(exp.getTime() + 7 * 24 * 60 * 60 * 1000);
    // document.cookie = constant.SYSTEM_AVATAR_NAME + 'userName=' + escape(userName) + ';expires=' + exp.toGMTString();
    // if (autoLogin) {
    //   document.cookie = constant.SYSTEM_AVATAR_NAME + 'userPasswd' + "=" + escape(values.originPassword) + ";expires=" + exp.toGMTString();
    // } else {
    //   exp.setTime(exp.getTime() - 1);
    //   document.cookie = constant.SYSTEM_AVATAR_NAME + 'userPasswd' + "=" + escape('') + ";expires=" + exp.toGMTString();
    // }
  };

  const handleRedirect = () => {
    const urlParams = new URL(window.location.href);
    const params = getPageQuery();
    message.success('登录成功');
    // localStorage.setItem('umi-locale', localStorage.getItem('umi-locale') || 'zh-CN');
    let { redirect } = params;
    let url = '/dashboard/blog';
    if (redirect) {
      const redirectUrlParams = new URL(redirect);
      if (redirectUrlParams.origin === urlParams.origin) {
        redirect = redirect.substr(urlParams.origin.length);
        if (redirect.match(/^\/.*#/)) {
          redirect = redirect.substr(redirect.indexOf('#') + 1);
          url = redirect;
        }
      }
    }
    history.push(url);
  };

  // const loadUserGroups = () => {
  //   const v = form.getFieldsValue();
  //   if (!v.userName || !v.userPasswd) {
  //     return;
  //   }
  //   v.userPasswd = md5(v.userPasswd);
  //   api.user.validateUserForDepartments(v).subscribe({
  //     next: (res) => {
  //       const code = res.code;
  //       if (code != 200) {
  //         setBeError(true);
  //         setErrorMessage(res.message);
  //         return;
  //       } else {
  //         setBeError(false);
  //         setErrorMessage('');
  //       }
  //       let groups = res.data;
  //       let deptId;
  //       const list = [];
  //       forEach((v) => {
  //         if (!deptId) {
  //           deptId = v.groupId;
  //         }
  //         let companyName = v.companyName;
  //         if (isNil(companyName)) {
  //           companyName = '';
  //         }
  //         list.push({ label: (companyName && (companyName + '-')) + v.groupName, value: v.groupId });
  //       }, groups);
  //       setOptions(list);
  //       form.setFieldsValue({ groupId: deptId });
  //     }
  //   });
  // }
  // const delayedQuery = useRef(debounce(() => loadUserGroups(), 200)).current;

  const doFinish = (v) => {
    setLoading(true);
    v.systemTag = 'admin';
    v.userPasswd = md5(v.userPasswd);
    v.originPassword = v.userPasswd
    api.user.login(v, v.systemTag).subscribe({
      next: (data) => {
        const resp = data[0];
        handleRemeberMe(v);
        handleToken(resp.access_token);
        handleRedirect();
        api.user.loadUserButtons().subscribe({
          next: (br) => {
            sessionStorage.setItem(constant.KEY_USER_BUTTON_PERMS, br || []);
          }
        });

      }
    }).add(() => setLoading(false));
  }

  // const [doFinish] = useObservableAutoCallback((event) =>
  //   event.pipe(
  //     debounceTime(400),
  //     distinctUntilChanged(),
  //     tap(() => setLoading(true)),
  //     switchMap((v) => {
  //       v.systemTag = 'admin';
  //       v.userPasswd = md5(v.userPasswd);
  //       return api.user.login(v).pipe(tap(handleRemeberMe(v)));
  //     }),
  //     map((data) => data[0]),
  //     tap((v) => handleToken(v.access_token)),
  //     switchMap(() => {
  //       return api.user.loadUserButtons();
  //     }),
  //     tap((br) => sessionStorage.setItem(constant.KEY_USER_BUTTON_PERMS, br || [])),
  //     tap((v) => handleRedirect()),
  //     shareReplay(1),
  //   ), () => setLoading(false)
  // );

  return (
    <div className={styles.main}>
      <Form
        name="basic"
        initialValues={{
          autoLogin: checked,
          userName: userName,
          userPasswd: userPasswd,
        }}
        autoComplete="off"
        className="snam-form"
        form={form}
        onFinish={(values) => {
          // objectAssign(values, { userPasswd: md5(values.userPasswd), originPassword: values.userPasswd });
          // values.systemTag = 'business' + values.groupId;
          doFinish(values);
        }}
      >
        {beError && (
          <LoginMessage
            content={errorMessage}
          />)}
        <Form.Item name="userName" label="账号" rules={[
          {
            required: true,
            message: '请输入账号!'
          },
        ]}>
          <Input
            autoFocus={true}
            // onBlur={delayedQuery}
            prefix={<UserOutlined className={styles.prefixIcon} />}
            placeholder="请输入账号"
            style={{ background: 'rgba(255, 255, 255, 0.5)', backdropFilter: '5px' }}
          />
        </Form.Item>
        <Form.Item name="userPasswd" label="密码" rules={[
          {
            required: true,
            message: '请输入密码！'
          },
        ]}>
          <Input.Password
            // onBlur={delayedQuery}
            prefix={<LockTwoTone className={styles.prefixIcon} />}
            placeholder="请输入密码"
            style={{ background: 'rgba(255, 255, 255, 0.5)', backdropFilter: '5px' }}
          />
        </Form.Item>
        {/* <Form.Item name="groupId" label="组织" rules={[{ required: true, message: "请选择组织!" }]}>
          <Select
            options={options}
            prefix={<ApartmentOutlined />}
            placeholder="请选择组织"
          />
        </Form.Item> */}
        <div style={{ marginLeft: '54px', marginBottom: '30px' }}>
          <Form.Item name="autoLogin" valuePropName="checked" noStyle >
            <Checkbox>记住密码</Checkbox>
          </Form.Item>
        </div>
        <div style={{ marginLeft: '54px' }}>
          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              size="large"
              shape="round"
              style={{ width: '200px' }}
              loading={loading}
            >
              登录
            </Button>
          </Form.Item>
        </div>
      </Form>
    </div>
  );
};

// src/pages/login/index.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <div class="login-header">
        <img src="@/assets/logo.png" alt="Logo" class="logo" />
        <h1>{{ constant.SYSTEM_LOGIN_TITLE }}</h1>
        <p>{{ constant.SYSTEM_LOGIN_DESC }}</p>
      </div>
      
      <el-alert
        v-if="errorMessage"
        :title="errorMessage"
        type="error"
        :closable="false"
        style="margin-bottom: 24px"
      />
      
      <el-form
        ref="loginFormRef"
        :model="loginForm"
        :rules="rules"
        @submit.prevent="handleSubmit"
      >
        <el-form-item prop="userName">
          <el-input
            v-model="loginForm.userName"
            placeholder="用户名"
            size="large"
            :prefix-icon="User"
          />
        </el-form-item>
        
        <el-form-item prop="userPasswd">
          <el-input
            v-model="loginForm.userPasswd"
            type="password"
            placeholder="密码"
            size="large"
            :prefix-icon="Lock"
            @keyup.enter="handleSubmit"
          />
        </el-form-item>
        
        <el-form-item>
          <el-checkbox v-model="loginForm.autoLogin">记住密码</el-checkbox>
        </el-form-item>
        
        <el-form-item>
          <el-button
            type="primary"
            size="large"
            :loading="loading"
            style="width: 100%"
            @click="handleSubmit"
          >
            登录
          </el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { User, Lock } from '@element-plus/icons-vue';
import { ElMessage } from 'element-plus';
import { api, constant, isEmpty, md5 } from '@/common/utils';

const router = useRouter();
const loginFormRef = ref(null);
const loading = ref(false);
const errorMessage = ref('');

const loginForm = reactive({
  userName: '',
  userPasswd: '',
  autoLogin: false,
});

const rules = {
  userName: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
  ],
  userPasswd: [
    { required: true, message: '请输入密码', trigger: 'blur' },
  ],
};

// 读取 Cookie
const getCookie = (name) => {
  const arr = document.cookie.match(new RegExp('(^| )' + name + '=([^;]*)(;|$)'));
  if (arr) return unescape(arr[2]);
  return null;
};

// 设置 Cookie
const setCookie = (name, value, days = 7) => {
  const exp = new Date();
  exp.setTime(exp.getTime() + days * 24 * 60 * 60 * 1000);
  document.cookie = name + '=' + escape(value) + ';expires=' + exp.toGMTString();
};

// 删除 Cookie
const deleteCookie = (name) => {
  const exp = new Date();
  exp.setTime(exp.getTime() - 1);
  document.cookie = name + '=;expires=' + exp.toGMTString();
};

// 初始化表单数据
onMounted(() => {
  const savedUserName = getCookie(constant.SYSTEM_AVATAR_NAME + 'userName');
  const savedPassword = getCookie(constant.SYSTEM_AVATAR_NAME + 'userPasswd');
  
  if (savedUserName) {
    loginForm.userName = savedUserName;
  }
  if (savedPassword) {
    loginForm.userPasswd = savedPassword;
    loginForm.autoLogin = true;
  }
});

// 处理登录
const handleSubmit = async () => {
  if (!loginFormRef.value) return;
  
  await loginFormRef.value.validate(async (valid) => {
    if (!valid) return;
    
    loading.value = true;
    errorMessage.value = '';
    
    try {
      const params = {
        userName: loginForm.userName,
        userPasswd: md5(loginForm.userPasswd),
        originPassword: loginForm.userPasswd,
      };
      
      // 调用登录 API
      const subscription = api.user.login(params).subscribe({
        next: (data) => {
          if (data && data.token) {
            // 保存 token
            const token = `Bearer ${data.token}`;
            sessionStorage.setItem(constant.KEY_USER_TOKEN, token);
            
            // 记住密码
            if (loginForm.autoLogin) {
              setCookie(constant.SYSTEM_AVATAR_NAME + 'userName', loginForm.userName);
              setCookie(constant.SYSTEM_AVATAR_NAME + 'userPasswd', loginForm.userPasswd);
            } else {
              deleteCookie(constant.SYSTEM_AVATAR_NAME + 'userName');
              deleteCookie(constant.SYSTEM_AVATAR_NAME + 'userPasswd');
            }
            
            ElMessage.success('登录成功');
            router.push('/');
          } else {
            errorMessage.value = '登录失败，请检查用户名和密码';
          }
        },
        error: (err) => {
          errorMessage.value = err.message || '登录失败，请稍后重试';
          loading.value = false;
        },
        complete: () => {
          loading.value = false;
        },
      });
    } catch (error) {
      errorMessage.value = '登录失败，请稍后重试';
      loading.value = false;
    }
  });
};
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-box {
  width: 400px;
  padding: 40px;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.logo {
  width: 64px;
  height: 64px;
  margin-bottom: 16px;
}

.login-header h1 {
  font-size: 24px;
  font-weight: 600;
  margin: 0 0 8px;
  color: #333;
}

.login-header p {
  font-size: 14px;
  color: #666;
  margin: 0;
}
</style>
